# Generated by Django 6.1 on 2026-10-06 05:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Grocery categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Litre (l)'), ('ml', 'Millilitre (ml)'), ('pcs', 'Pieces'), ('pack', 'Packet')], default='kg', max_length=10)),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Low-stock alert shows when stock is at or below this level.', max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='store.grocerycategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Stock In (purchase / received)'), ('OUT', 'Stock Out (used / wasted)'), ('ADJUST', 'Correction (set exact count)')], max_length=6)),
                ('change', models.DecimalField(decimal_places=3, max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='store.groceryitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
