# Generated by Django 6.1 on 2026-10-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In (purchase / received)'), ('OUT', 'Stock Out (used / wasted)'), ('ADJUST', 'Correction (set exact count)'), ('DAMAGE', 'Damaged'), ('EXPIRY', 'Expired')], max_length=6),
        ),
    ]
