from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.admin_dashboard, name='admin_home'),
    path('menu/', views.manage_menu, name='manage_menu'),
    path('menu/add/', views.add_menu_item, name='add_menu_item'),
    path('menu/edit/<int:pk>/', views.edit_menu_item, name='edit_menu_item'),
    path('menu/delete/<int:pk>/', views.delete_menu_item, name='delete_menu_item'),
    path('tables/', views.manage_tables, name='manage_tables'),
    path('tables/add/', views.add_table, name='add_table'),
    path('tables/edit/<int:pk>/', views.edit_table, name='edit_table'),
    path('tables/delete/<int:pk>/', views.delete_table, name='delete_table'),
    path('tables/<int:pk>/open/', views.open_table, name='open_table'),
    path('bookings/', views.manage_bookings, name='manage_bookings'),
    path('bookings/<int:pk>/approve/', views.approve_booking, name='approve_booking'),
    path('bookings/<int:pk>/reject/', views.reject_booking, name='reject_booking'),
    path('users/', views.manage_users, name='manage_users'),
    path('users/add-staff/', views.add_staff, name='add_staff'),
    path('users/bulk-action/', views.bulk_user_action, name='bulk_user_action'),
    path('orders/', views.manage_orders, name='manage_orders'),
    path('orders/<int:pk>/update-status/', views.api_order_status, name='api_order_status'),
    path('orders/<int:pk>/assign-table/', views.assign_table, name='assign_table'),
    path('orders/<int:pk>/mark-cash-received/', views.mark_cash_received, name='mark_cash_received'),
    path('orders/<int:pk>/mark-refunded/', views.mark_refunded, name='mark_refunded'),
    path('orders/<int:pk>/approve/', views.approve_order, name='approve_order'),
    path('orders/<int:pk>/reject/', views.reject_order, name='reject_order'),
    path('orders/<int:pk>/stock-check/', views.order_stock_check, name='order_stock_check'),
    path('grocery/', views.manage_grocery, name='manage_grocery'),
    path('grocery/<int:pk>/update/', views.update_grocery, name='update_grocery'),
    path('grocery/<int:pk>/delete/', views.delete_grocery, name='delete_grocery'),
    path('reports/', views.sales_reports, name='sales_reports'),
    path('kitchen/', views.kitchen_dashboard, name='kitchen_dashboard'),
    path('kitchen/<int:pk>/status/<str:new_status>/', views.update_order_status, name='update_order_status'),
    path('kitchen/grocery/<int:pk>/update/', views.kitchen_update_grocery, name='kitchen_update_grocery'),
    path('server/', views.server_dashboard, name='server_dashboard'),
    path('server/poll/', views.server_poll, name='server_poll'),
    path('server/take-order/', views.server_take_order, name='server_take_order'),
    path('server/free-table/<int:pk>/', views.server_free_table, name='server_free_table'),
    path('delivery/', views.delivery_dashboard, name='delivery_dashboard'),
    path('delivery/poll/', views.delivery_poll, name='delivery_poll'),
    path('notifications/poll/', views.notifications_poll, name='notifications_poll'),
    path('notifications/read/', views.notifications_mark_read, name='notifications_mark_read'),
    path('table-qr-codes/', views.table_qr_codes, name='table_qr_codes'),
    path('kitchen/stock/', views.kitchen_stock, name='kitchen_stock'),
    path('kitchen/stock/<int:pk>/request/', views.kitchen_request_stock, name='kitchen_request_stock'),
    path('kitchen/notifications/poll/', views.kitchen_notifications_poll, name='kitchen_notifications_poll'),
    path('kitchen/stock-update/', views.kitchen_stock_update, name='kitchen_stock_update'),
    path('menu/<int:pk>/toggle/', views.toggle_menu_availability, name='toggle_menu_availability'),
    path('server/send-to-kitchen/<int:pk>/', views.server_send_to_kitchen, name='server_send_to_kitchen'),
    path('server/reject/<int:pk>/', views.server_reject_order, name='server_reject_order'),
]