# Generated by Django 6.1 on 2026-09-30 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_groceryitem'),
        ('menu', '0003_fooditem_is_veg'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_serving', models.DecimalField(decimal_places=3, help_text="In the grocery item's own unit (e.g. 0.250 for 250 g if unit is kg)", max_digits=8)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='menu.fooditem')),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='dashboard.groceryitem')),
            ],
            options={
                'unique_together': {('food_item', 'grocery')},
            },
        ),
    ]
