# Generated by Django 6.1 on 2026-09-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('served', 'Order served'), ('stock', 'Kitchen stock update')], default='served', max_length=20),
        ),
    ]
