# Generated by Django 6.1 on 2026-10-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_notification_kind_stockrequest'),
        ('store', '0002_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='store_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_uses', to='store.groceryitem'),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='store_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reports', to='store.groceryitem'),
        ),
    ]
