# Generated by Django 6.1 on 2026-10-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_recipeingredient_store_item_stockrequest_store_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('served', 'Order served'), ('rejected', 'Order rejected'), ('ready', 'Order ready'), ('out_for_delivery', 'Out for delivery'), ('stock', 'Kitchen stock update'), ('stock_in', 'Store stock update'), ('stock_out', 'Out of stock alert')], default='served', max_length=20),
        ),
    ]
