# Generated by Django 6.1 on 2026-10-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('kitchen', 'Kitchen Staff'), ('server', 'Server / Waiter'), ('store', 'Store Manager')], max_length=10),
        ),
    ]
