# Generated by Django 6.1 on 2026-09-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='occasion',
            field=models.CharField(blank=True, choices=[('none', 'No specific occasion'), ('birthday', '🎂 Birthday'), ('anniversary', '💍 Anniversary'), ('family', '👨\u200d👩\u200d👧 Family Gathering'), ('business', '💼 Business Meeting'), ('date', '❤️ Date Night'), ('other', '✨ Other')], default='none', max_length=20),
        ),
    ]
