# Generated by Django 6.1 on 2026-09-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_table_tablebooking_status_tablebooking_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablebooking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='table',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
