# Generated by Django 6.1 on 2026-09-04 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_table_tablebooking_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='occasion',
            field=models.CharField(blank=True, choices=[('none', 'No specific occasion'), ('birthday', '🎂 Birthday'), ('anniversary', '💍 Anniversary'), ('family', '👨\u200d👩\u200d👧 Family Gathering'), ('business', '💼 Business Meeting'), ('date', '❤️Date Night'), ('other', '✨ Other')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking.table'),
        ),
    ]
