# Generated by Django 6.1 on 2026-09-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_tablebooking_occasion_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
