# Generated by Django 6.1 on 2026-09-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_table_is_active_tablebooking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='tablebooking',
            name='status',
        ),
    ]
