# Generated by Django 6.1 on 2026-09-08 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_table_is_active_remove_tablebooking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='occasion',
            field=models.CharField(choices=[('none', 'No specific occasion'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('family', 'Family gathering'), ('business', 'Business meeting'), ('date', 'Date night'), ('other', 'Other')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='special_request',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
