# Generated by Django 6.1.1 on 2026-09-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_table_capacity_alter_tablebooking_occasion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
