# Generated by Django 6.1 on 2026-10-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_tablebooking_released_tablebooking_released_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Waiting for admin approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
