# Generated by Django 6.1 on 2026-10-07 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_tablebooking_decided_at_tablebooking_reject_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='extra_tables',
            field=models.ManyToManyField(blank=True, related_name='extra_bookings', to='booking.table'),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='guests',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
