# Generated by Django 6.1.1 on 2026-09-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_images/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='menu.fooditem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
