# Generated by Django 6.1.1 on 2026-09-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_fooditemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
