# Generated by Django 6.1 on 2026-10-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_fooditem_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='auto_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
