# Generated by Django 6.1.1 on 2026-09-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon_order_discount_amount_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_released',
            field=models.BooleanField(default=False),
        ),
    ]
