# Generated by Django 6.1 on 2026-10-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrival_time',
            field=models.DateTimeField(blank=True, help_text='When the customer will arrive. Blank means as soon as possible.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine-in'), ('takeaway', 'Take away')], default='dine_in', max_length=10),
        ),
    ]
